repos:
  - repo: https://github.com/psf/black
    rev: 21.8b0
    stages: [manual]
    hooks:
      - id: black

  - repo: https://github.com/timothycrosley/isort
    rev: 5.9.3
    stages: [manual]
    hooks:
      - id: isort

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        # TODO: Remove --exit-zero when we're done testing
        entry: pflake8 --exit-zero
        additional_dependencies:
          - pyproject-flake8
          - flake8-black
          - flake8-isort

  - repo: local
    stages: [manual]
    hooks:
      - id: lock-requirements
        name: Lock poetry requirements
        entry: poetry lock --no-update
        language: system
        files: "^pyproject.toml$"
        pass_filenames: false
      - id: export-requirements
        name: Export pyproject.toml -> requirements.txt
        entry: poetry export --without-hashes -o requirements.txt
        language: system
        files: "^pyproject.toml$"
        pass_filenames: false
      - id: export-requirements-dev
        name: Export pyproject.toml -> requirements-dev.txt
        entry: poetry export --without-hashes --dev -o requirements-dev.txt
        language: system
        files: "^pyproject.toml$"
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    stages: [manual]
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: fix-byte-order-marker
      - id: mixed-line-ending
