control_limit:
  cart_position: 0.15
  cart_velocity: 2.0
  cart_acceleration: 3.0
hardware_limit:
  cart_position: 0.20
  cart_velocity: 3.0
  cart_acceleration: 5.0
parameters:
  b: 0.30
  g: 9.81
  k: 0.20
