site_name: CartPole
site_url: https://robotics-laboratory.github.io/cart-pole/
repo_url: https://github.com/robotics-laboratory/cart-pole/
repo_name: robotics-laboratory/cart-pole

nav:
  - Quickstart: quickstart.md
  - Dynamics: dynamics.md
  - Reference:
      - reference/common.md
      - reference/log.md
      - reference/simulator.md

theme:
  name: material
  palette:
    primary: deep orange
  features:
    - content.code.copy
    - content.tabs.link

extra:
  version:
    default: latest
    provider: mike

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      toc_depth: 2


extra_css:
  - https://tikzjax.com/v1/fonts.css

extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://tikzjax.com/v1/tikzjax.js

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            allow_inspection: false
            docstring_section_style: spacy
            docstring_style: numpy
            heading_level: 2
            line_length: 100
            members_order: source
            show_bases: false
            show_root_heading: true
            show_signature_annotations: true
            show_source: true
