[tool.poetry]
name = "cart_pole"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "~3.8"
matplotlib = "^3.4.3"
numpy = "^1.21.2"
pybullet = "^3.1.8"
scipy = "^1.7.1"
serial = "^0.0.97"
aiohttp = "^3.7.4"

[tool.poetry.dev-dependencies]
black = "^21.8b0"
flake8 = "^3.9.2"
pre-commit = "^2.15.0"
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
