environment:
  state_size: 5
  action_size: 1
  max_action: 1
  delta: 0.1

trainer:
  device_name: cpu
  gamma: 0.99                    
  max_buffer_size: 10**5       
  start_timesteps: 5000      
  timesteps_per_epoch: 1        
  batch_size: 128               
  max_grad_norm: 10             
  tau: 0.005                     
  policy_update_freq: 1
  alpha: 0.1 

actor:
  lr: 3e-4
  tau: 1
  layer_sizes:
    - 256
    - 256
    - 256

critic:
  lr_1: 3e-4
  lr_2: 3e-4
  tau: 1
  layers:
    - 256
    - 256
    - 256