environment:
  state_size: 5
  action_size: 1
  max_action: 1
  delta: 0.1

trainer:
  batch_size: 1024
  discount: 0.99
  device_name: cpu

  memory_size: 1000000

  warmup:
    steps: 1000
    use_random_position: true

actor:
  lr: 1e-3
  tau: 1
  layer_sizes:
    - 256
    - 256
    - 256

critic:
  lr: 1e-3
  tau: 1
  layers:
    - 256
    - 256
    - 256
