name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with: { python-version: 3.9 }
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with: { virtualenvs-create: false }
      - name: Install requirements
        run: poetry install --no-root
      - name: Run pre-commit hooks
        run: pre-commit run --all-files --show-diff-on-failure
      - name: Run tests
        run: pytest
