name: docs

on:
  push:
    branches:
      - readthedocs
      - cart-pole-3
      - master

permissions:
  contents: write

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      # TODO: Add proper chaching
      # TODO: Maybe use poetry-based action
      - run: pip install mkdocs-material mike poetry
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - run: mike deploy --rebase --push --update-aliases $(poetry version -s) latest
